### ISSUE TITLE
Form vs dropdown

### ISSUE THREAD

**Issue by SridharShrinidhi** [SridharShrinidhi/animal-rescue-website#1]
@hellachella @thomasjbradley
Markbot keeps asking for a label associated with an input tag, but the input tag in this case is for a toggle nav. I have attached screenshots below.

<img width="497" alt="screen shot 2018-01-02 at 4 56 06 pm" src="https://user-images.githubusercontent.com/22351855/34501649-d8299fde-efdd-11e7-86f5-45a1386ea25e.png">

<img width="739" alt="screen shot 2018-01-02 at 4 55 41 pm" src="https://user-images.githubusercontent.com/22351855/34501640-ccfc31d0-efdd-11e7-9073-51b5c0ea293a.png">

**Comment by thomasjbradley** [comment]
Because there is only an `<img>` inside the `<label>` tag the information isn't terribly accessible. Have you tried adding the `aria-label` attribute onto the `<label>` tag itself?

**Comment by SridharShrinidhi** [comment]
That was the problem. Thank you so much!
