### ISSUE TITLE
Internet-Android

### ISSUE THREAD

**Issue by fakeha-abdullah** [SridharShrinidhi/animal-rescue-website#7]
-homepage ( at the bottom of the page the word donate is slightly upwards. Try pushing it down a bit.
-When I open the tab bar for the navigation , the orange bar doesn't cover the FAQ and Shop section.
-The breed/age dropdown buttons need more padding.
- The application page contains a bit of large spacing between some questions.

**Comment by SridharShrinidhi** [comment]
> -homepage ( at the bottom of the page the word donate is slightly upwards. Try pushing it down a bit. 
Font is designed that way. 

> -When I open the tab bar for the navigation , the orange bar doesn't cover the FAQ and Shop section.
Fixed

> The application page contains a bit of large spacing between some questions.

Fixed
